title: "Angie Cardona"
description: "Desarrolladora Backend Junior enfocada en Python, Django y bases de datos SQL. Enfocada en la mejora continua y la entrega de proyectos de alta calidad que resuelvan problemas reales. Mira mis <span class='highlight'>últimos trabajos</span>."

  # Asegúrate de incluir la barra inicial
author: "Angie Cardona"

# Definición de la colección de proyectos
collections:
  projects:
    output: true
    permalink: /proyectos/:title/

# Configuración adicional (opcional)
baseurl: "/Portafolio"
theme: minima

plugins:
  - jekyll-feed
